### ISSUE TITLE
C# name convention (Method)

### ISSUE THREAD

**Issue by gaufung** [megaease/easeagent-sdk-net#5]
`Tracers/Zipkin/V2/V1SpanConvert` method's name doesn't follow the `C#` name convention

**Comment by observeralone** [comment]
According to the naming convention, the first letter of a `private` method should be lowercase. Please take a close look. 
I will close this `issue`, or you can close it yourself unless you can provide a more convincing reason.

**Comment by observeralone** [comment]
Maybe you are right, although I don't think making `public` and `private` naming conventions consistent is a good choice. However, I respect everyone's decision.
Adjust: #6
